### ISSUE TITLE
Is it possible to make Docker command work for MacOS?

### ISSUE THREAD

**Issue by kpritam** [gvolpe/sbt-nix.g8#5]
```
nix-build nix/docker.nix -o result-base-jre
```

Above command results into following error on MacOS (x86_64-darwin arch)

```
"architecture": "Can't map Nix system x86_64-darwin to Docker architecture notation. Please check that your input and your requested build are correct or update the mapping in Nixpkgs."
```

**Comment by gvolpe** [comment]
No, `darwin` architecture is not supported by `docker`, that's unrelated to Nix. What I'd recommend is to have a CI building the images (on Linux) and pull those images locally.

It should be possible, though, to build Docker images on Max using Nix by specifying `x86_64-linux` as the architecture but I'm not really familiar with Apple stuff.

**Comment by gvolpe** [comment]
Closing this issue as I enabled the new discussions feature for further questions.
